import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Context from "../context/Context";
import Link from "next/link";
import { PiWhatsappLogoFill } from "react-icons/pi";
import "./components/styles/layout.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Context>
            <div
              className="fixed-bottom"
              style={{ marginBottom: 30, marginLeft: 30 }}
            >
              <Link
                className="show-tool-tip"
                href="https://wa.me/917706087842"
                style={{ textDecoration: "none" }}
                target="_blank"
              >
                <div
                  className="whatsapp"
                  style={{
                    width: 200,
                    color: "white",
                    backgroundColor: "green",
                    fontSize: 15,
                    display: "none",
                    borderRadius: 6,
                    padding: 10,
                  }}
                >
                  <p>If you want Customized Product.</p>
                  <p>Chat With Us To Get Customized Products.</p>
                </div>

                <PiWhatsappLogoFill
                  style={{ width: 50, height: 50, color: "green" }}
                />
              </Link>
            </div>
            {children}
          </Context>
        </AuthProvider>
      </body>
    </html>
  );
}
